export const seoConfig = {
	title: {
		default: "ConfigsHub - Modern Configuration Management Platform",
		template: "%s | ConfigsHub",
	},
	description:
		"Secure, scalable configuration management for modern applications. Store, version, and deploy your app configs with enterprise-grade security and Apple-inspired design.",
	keywords: [
		"configuration management",
		"app config",
		"environment variables",
		"config deployment",
		"secure configuration",
		"devops tools",
		"application settings",
		"config versioning",
		"configuration as code",
		"modern development tools",
		"enterprise config management",
		"cloud configuration",
		"microservices config",
		"kubernetes config",
		"docker configuration",
		"CI/CD configuration",
		"infrastructure as code",
		"config automation",
		"secure secrets management",
		"multi-environment config",
	],
	authors: [{ name: "ConfigsHub Team", url: "https://configshub.dev" }],
	creator: "ConfigsHub",
	publisher: "ConfigsHub",
	applicationName: "ConfigsHub",
	generator: "Next.js",
	referrer: "origin-when-cross-origin",
	category: "Developer Tools",
	classification: "Business",
	openGraph: {
		type: "website",
		locale: "en_US",
		url: "https://configshub.dev",
		siteName: "ConfigsHub",
		title: "ConfigsHub - Modern Configuration Management Platform",
		description:
			"Transform how you manage application configurations with our secure, scalable platform featuring Apple-inspired design and enterprise-grade security.",
		images: [
			{
				url: "/og-image.png",
				width: 1200,
				height: 630,
				alt: "ConfigsHub - Modern Configuration Management Platform",
				type: "image/png",
			},
			{
				url: "/og-image-square.png",
				width: 1200,
				height: 1200,
				alt: "ConfigsHub Logo",
				type: "image/png",
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		site: "@configshub",
		creator: "@configshub",
		title: "ConfigsHub - Modern Configuration Management Platform",
		description: "Secure, scalable configuration management for modern applications with Apple-inspired design.",
		images: ["/twitter-image.png"],
	},
	robots: {
		index: true,
		follow: true,
		noarchive: false,
		nosnippet: false,
		noimageindex: false,
		nocache: false,
		googleBot: {
			index: true,
			follow: true,
			noimageindex: false,
			"max-video-preview": -1,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},
	verification: {
		google: "your-google-verification-code",
		yandex: "your-yandex-verification-code",
		yahoo: "your-yahoo-verification-code",
		other: {
			me: ["your-email@configshub.dev", "https://configshub.dev"],
		},
	},
	alternates: {
		canonical: "https://configshub.dev",
		types: {
			"application/rss+xml": "https://configshub.dev/rss.xml",
			"application/atom+xml": "https://configshub.dev/atom.xml",
		},
	},
	other: {
		"google-site-verification": "your-google-verification-code",
		"msvalidate.01": "your-bing-verification-code",
		"yandex-verification": "your-yandex-verification-code",
	},
};

export const jsonLdData = {
	organization: {
		"@type": "Organization",
		"@id": "https://configshub.dev/#organization",
		name: "ConfigsHub",
		url: "https://configshub.dev",
		logo: {
			"@type": "ImageObject",
			url: "https://configshub.dev/logo.png",
			width: 512,
			height: 512,
		},
		description: "Modern configuration management platform for developers",
		foundingDate: "2024",
		contactPoint: {
			"@type": "ContactPoint",
			contactType: "customer service",
			email: "support@configshub.dev",
		},
		sameAs: [
			"https://twitter.com/configshub",
			"https://github.com/configshub",
			"https://linkedin.com/company/configshub",
		],
	},
	software: {
		"@type": "SoftwareApplication",
		"@id": "https://configshub.dev/#software",
		name: "ConfigsHub",
		description: "Modern configuration management platform for developers and DevOps teams",
		url: "https://configshub.dev",
		applicationCategory: "DeveloperApplication",
		operatingSystem: "Web Browser",
		softwareVersion: "1.0.0",
		releaseNotes: "Initial release with core configuration management features",
		downloadUrl: "https://configshub.dev",
		installUrl: "https://configshub.dev/auth/signup",
		screenshot: "https://configshub.dev/screenshot.png",
		offers: {
			"@type": "AggregateOffer",
			priceCurrency: "USD",
			lowPrice: "0",
			highPrice: "99",
			offerCount: "3",
		},
		aggregateRating: {
			"@type": "AggregateRating",
			ratingValue: "4.8",
			reviewCount: "150",
			bestRating: "5",
			worstRating: "1",
		},
		featureList: [
			"Enterprise Security",
			"Version Control",
			"Multi-Environment Support",
			"Access Control",
			"API Integration",
			"Real-time Deployment",
			"Audit Trails",
			"Team Collaboration",
			"Backup & Recovery",
			"Compliance Reporting",
		],
	},
};
